version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && mailcatcher --ip=0.0.0.0 && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/desafio_petbooking
      - /desafio_petbooking/tmp
    ports:
      - "3000:3000"
      - "1080:1080"
    depends_on:
      - db